### PR TITLE
Fix search button in mobile view

### LINKED ISSUE #118: Make Search icon clickable when main menu is open, closing main menu
On mobile, when Library submenu is open (displaying Favorites Collection Playlists History X), the Search icon is becomes unclickable. The user needs to click the X and close their menu before being able to use Search, but it is unlikely the user will know this is the reason Search is "not working".

On mobile, whenever the user clicks the Search icon, it should automatically close their main menu and open the search bar.

### PR DESCRIPTION
**Pull request by fgblomqvist**
Closes #118 (the UX issues pointed out by @gitaaron should be moved to a separate issue).

The gist is this: the search element was not being rendered when a submenu was.

I took some liberty to also do some refactoring that I think would help avoid issues like this, or at least make it easier to read/debug the code, in the future. I'll put some review comments to clarify.

I'm open to discuss any of the changes of course :slightly_smiling_face:.

(I'd recommend hiding whitespace when reviewing)

### CODE REVIEW

File: beta/components/header/index.js [hunk 1]
```diff
@@ -167,7 +167,7 @@ class Header extends Component {
     this.local.resolved = props.resolved
     this.local.href = props.href
 
-    const nav = () => {
+    const mainMenu = () => {
```
Comment (fgblomqvist) [inline beta/components/header/index.js:170]: Renamed this to avoid ambiguity, it's not just a nav that is rendered all the time, but specifically the "main one" (open to other names).

File: beta/components/header/index.js [hunk 2]
```diff
@@ -276,19 +276,16 @@ class Header extends Component {
...
-      `
+    // Figure out which menu to render, only one can render at a time
+    let menu;
+    if (this.local.machine.state.library === 'on') {
+      menu = this.renderSubMenuItems({ name: 'library', eventName: 'library:toggle' }, this.local.machine)
+    } else if (this.local.machine.state.browse === 'on') {
+      menu = this.renderSubMenuItems({ name: 'browse', eventName: 'browse:toggle' }, this.local.machine)
+    } else {
+      menu = mainMenu()
     }
```
Comment (fgblomqvist) [inline beta/components/header/index.js:287]: Rather than using a complex dictionary/OR chain to figure out what to render in a single statement, I think using a normal control flow with if statements is easier to follow, at least for this statement. It reads more like how a human would think. Now you can easily see that when state X is Y, we render this specific menu, and when state Z is A, we render a different one, and so forth.

File: beta/components/header/index.js [hunk 3]
```diff
@@ -344,83 +341,82 @@ class Header extends Component {
             </li>
           </ul>
         </nav>
-        ${subMenu()}
+        ${this.renderSearch()}
```
Comment (fgblomqvist) [inline beta/components/header/index.js:344]: The most important part was ensuring that the search always renders.

File: beta/components/header/index.js [hunk 4]
```diff
@@ -344,83 +341,82 @@ class Header extends Component {
...
+        ${menu}
       </header>
     `
   }
 
   renderSubMenuItems ({ name = 'library', eventName }, machine) {
-    return () => {
```
Comment (fgblomqvist) [inline beta/components/header/index.js:353]: I didn't see a reason for why `renderSubMenuItems` should return a function, so I simplified that away.

**Review by peterklingelhofer — APPROVED** [review]
These changes work for me, and make the website work exactly how I would expect it, you can search and switch between the various links at the bottom in tandem.

I also couldn't find a reason why `renderSubMenuItems` should return a function, so that change also makes sense to me.
