### PR TITLE
Fix menu icons on tracks for iOS

### LINKED ISSUE #187: [mobile/iOS only] Tiny back arrow & ellipse icons
### Operating system
iOS

### Browser name and version
* Firefox
* Safari
* Expo app on iOS

### Expected behavior
Regular icon size for back arrows and track options on mobile.

### Actual behavior
Miniscule icons.

### Steps to reproduce behavior
Moving this issue from [here](https://github.com/peterklingelhofer/stream-app/issues/14) as it has to be addressed in this repo.

Not sure how to handle this navigation issue. Check image:
* Firefox
* Safari
* Expo app on iOS

little back arrow is just a dot on the Expo app.

The ellipse icons to present a user with additional options for each track also appear to be affected by this bug.

image
IMG_9179

### PR DESCRIPTION
**Pull request by peterklingelhofer**
Since https://github.com/resonatecoop/stream/pull/215 was reverted, this should hopefully be a safer implementation. Since `window.navigator` is undefined with jalla, we check first and ensure that it is defined before proceeding with any iOS-specific logic.

#### Before
IMG_9198

#### After
IMG_9195

This closes https://github.com/resonatecoop/stream/issues/187.

### CODE REVIEW

File: packages/track-component/index.js [hunk 1]
```diff
@@ -156,17 +156,27 @@ class Track extends Component {
...
-      selection: Object.entries(selection).filter(([k, v]) => Boolean(v)).map(([k, v]) => k), // selection to array of keys
-      data: Object.assign({}, this.local.track, {
-        count: this.local.count,
-        favorite: this.local.favorite || this.local.fav,
-        url: new URL(`/track/${this.local.track.id}`, process.env.APP_HOST || 'https://stream.resonate.coop')
-      }),
-      size: this.local.type === 'album' ? 'sm' : 'md', // button size
-      orientation: 'bottomright'
-    })
+    const iOS = (navigator !== undefined && 'userAgent' in navigator) &&
```
Comment (simonv3) [inline packages/track-component/index.js:159]: Between these two PRs, should this be a re-usable function?

Comment (peterklingelhofer) [reply packages/track-component/index.js:159]: Great idea @simonv3. I've also amended the capitalization to match the [Dart docs' capitalization](https://api.flutter.dev/flutter/dart-io/Platform/isIOS.html).

I get this error:
```
◇ ReferenceError: navigator is not defined
    at Object.<anonymous> (/Users/peterklingelhofer/Dev/stream/beta/build/helpers/isIOS.js:7:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/Users/peterklingelhofer/Dev/stream/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/Users/peterklingelhofer/Dev/stream/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/peterklingelhofer/Dev/stream/beta/build/views/settings/index.js:7:15)
```

Using this diff:
```diff
diff --git a/beta/src/views/settings/index.js b/beta/src/views/settings/index.js
index 568247f..71415c9 100644
--- a/beta/src/views/settings/index.js
+++ b/beta/src/views/settings/index.js
@@ -1,6 +1,7 @@
 const html = require('choo/html')
 const button = require('@resonate/button')
 const viewLayout = require('../../layouts/default')
+const isIOS = require('../../helpers/isIOS')
 
 module.exports = () => viewLayout(renderSettings)
 
@@ -20,12 +21,7 @@ function renderSettings (state, emit) {
     size: 'none'
   })
 
-  const cookieConsentGranted = state.cookieConsentStatus === 'allow'
-  const iOS = (navigator !== undefined && 'userAgent' in navigator) &&
-    (navigator.userAgent.match(/iOS/) ||
-    (navigator.userAgent.match(/Mac/) && document !== undefined && 'ontouchend' in document))
-
-  const notificationsSection = html`
+  const notificationSettings = html`
     <div class="bg-light-gray bg-light-gray--light bg-transparent--dark ba b--gray b--gray--light 
b--near-black--dark mb3 pa3">
       <fieldset class="pa0 ma0 bn">
         <legend class="f3 lh-title ma0 pa0">Notifications</legend>
@@ -37,7 +33,8 @@ function renderSettings (state, emit) {
     </div>
   `
 
-  const cookieConsentSection = html`
+  const cookieConsentGranted = state.cookieConsentStatus === 'allow'
+  const cookieConsentSettings = html`
     <div class="bg-light-gray bg-light-gray--light bg-transparent--dark ba b--gray b--gray--light 
b--near-black--dark mb3 pa3">
       <fieldset class="pa0 ma0 bn">
         <legend class="f3 lh-title ma0">Cookie consent</legend>
@@ -59,8 +56,8 @@ function renderSettings (state, emit) {
 
   return html`
     <section id="app-settings" class="flex flex-column ph4 mt3">
-      ${!iOS ? notificationsSection : ''}
-      ${cookieConsentSection}
+      ${!isIOS ? notificationSettings : ''}
+      ${cookieConsentSettings}
     </section>
   `
 }
```

Previous MR's I've tried tackling this issue had to be reverted due to `navigator is not defined` in places in jalla.

I even tried importing lodash and using `isNil`, same error:
```js
import { isNil } from 'lodash'

export const isIOS = (!isNil(navigator) && 'userAgent' in navigator) &&
    ((navigator.userAgent.match(/iOS/) ||
    (navigator.userAgent.match(/Mac/) && !isNil(document) && 'ontouchend' in document)))
```
