### PR TITLE
Clicking tag in search toggles search off

### LINKED ISSUE #210: Tag menu stays open after tag is clicked
### Operating system
iOS 15.3.1

### Browser name and version
[stream-app 1.1.1](https://github.com/peterklingelhofer/stream-app) (Safari)

### Expected behavior
Search > tap a tag > go to tag page, but tag menu closes.

### Actual behavior
Search > tap a tag > go to tag page, but tag menu stays open. Since it covers most of the screen it’s hard to know if I’m on the new tag page

### Steps to reproduce behavior
Search > tap a tag > go to tag page
original

### PR DESCRIPTION
**Pull request by peterklingelhofer**
These changes make it so on the Search bar and clicking a tag send you to that tag and de-focus the search bar, closing the search menu. Also, clicking an artist in your search history does the same. Hovering over an artist in search history underlines it.

This closes #210.

### CODE REVIEW

File: beta/src/components/header/index.ts [hunk 1]
```diff
@@ -433,14 +433,16 @@ class Header extends Component<HeaderProps> {
   }
 
   renderSearch (): HTMLElement {
+    const searchClasses: string = 'search flex-l flex-auto-l w-100-l justify-center-l'
     const search = {
       on: () => this.state.cache(Search, 'search').render({ tags: TAGS }),
       off: () => {
         const attrs = {
```
Comment (fgblomqvist) [inline beta/src/components/header/index.ts]: Unrelated to this PR, but this way of adding attrs to a button is quite odd imo. Better to just put them straight in the HTML (could always put them over multiple lines etc.) rather than add more complexity.

File: beta/src/components/header/index.ts [hunk 2]
```diff
@@ -433,14 +433,16 @@ class Header extends Component<HeaderProps> {
   }
 
   renderSearch (): HTMLElement {
+    const searchClasses: string = 'search flex-l flex-auto-l w-100-l justify-center-l'
```
Comment (fgblomqvist) [inline beta/src/components/header/index.ts]: Maybe I'm missing something, but what's the reason for adding the same classes to both the button and the div wrapping the button?

File: packages/search-component/index.js [hunk 3]
```diff
@@ -158,13 +165,20 @@ class Search extends Component {
...
-                      <a class="db lh-copy f5 link" href="/search?q=${name}">
-                        ${name}
-                      </a>
-                    </li>
-                  `
+                  ${this.local.artists.map(({ meta_value: name }) => {
+                    const clickSearchHistoryHandler = () => {
+                      document.getElementById(`search-history-href-${name}`).click()
+                      this.state.components.header.machine.emit('search:toggle')
+                    }
```
Comment (fgblomqvist) [inline packages/search-component/index.js]: I don't understand what is going on here, we're just forwarding the click from the visible anchor to the invisible one? Can't we just use a single anchor to achieve all we want (putting an onclick on an anchor shouldn't disable its default behavior...I think?).

**Review by fgblomqvist — COMMENTED** [review]
Maybe not urgent, but this project definitely needs an ARIA audit at some point :stuck_out_tongue:

File: beta/src/components/header/index.ts (hunk 2 above)
Comment (peterklingelhofer) [reply beta/src/components/header/index.ts]: I made these changes to expand the click hitbox for the Search after it's been closed, before it was hard to re-activate the search before after it was closed, you couldn't click very far above or below the icon/text nor far left or right. There may be a simpler way to make that change without doubling the classes up though. I'll investigate.

Comment (fgblomqvist) [reply beta/src/components/header/index.ts]: Perhaps just giving the button some extra padding? Haven't experimented myself but it's a thought 🙂

File: packages/search-component/index.js (hunk 3 above)
Comment (peterklingelhofer) [reply packages/search-component/index.js]: Pressing href on a button redirects to the artist page or tag without reloading the header, whereas with an onClick with location=href, it does. If you have any ideas for achieving this (go to new page from an onclick without reloading the header too) I'm all ears! The UX impression wasn't as good with the header reloading (for no good reason) made the website seem slower overall.

File: beta/src/components/header/index.ts (hunk 2 above)
Comment (peterklingelhofer) [reply beta/src/components/header/index.ts]: We definitely want the button to occupy all of the space the div occupies (if you test out this MR you'll see what I'm talking about), it's an unintuitively-narrow area you can click as it is currently if you close the search by pressing the x on the right side. I will experiment to see if I can consolidate things though!

File: packages/search-component/index.js (hunk 3 above)
Comment (fgblomqvist) [reply packages/search-component/index.js]: I assumed there was a way to navigate to a new page programmatically (as in, within the SPA framework) 😅 
I feel like I've seen an event you can emit perhaps (to which you pass the new path)? I can do some digging later, but I believe there is a way.

File: beta/src/components/header/index.ts (hunk 2 above)
Comment (fgblomqvist) [reply beta/src/components/header/index.ts]: Hmm okay fair enough. I think the correct setup would perhaps be this then:
```
div: search flex-l justify-center-l w-100-l
button: js bn dn db-l bg-transparent flex-l justify-center-l w-100-l
```
With this I get the desired UX/UI.

I'm assuming the `search` class should be specific to the button (since that's where it was used before) and the `flex-auto-l` class shouldn't be needed.

Comment (fgblomqvist) [reply beta/src/components/header/index.ts]: Also, to nag, maybe make sure the cursor is a pointer over this clickable area as well 😄

File: beta/src/components/header/index.ts [hunk 4]
```diff
@@ -433,14 +433,16 @@ class Header extends Component<HeaderProps> {
...
-          onclick: (e) => {
+          onclick: () => {
             this.local.machine.emit('search:toggle')
           },
-          class: 'js bn dn db-l bg-transparent'
+          class: `js bn dn db-l bg-transparent ${searchClasses}`,
+          style: 'height:3rem'
         }
         return html`
           <button ${attrs}>
```
Comment (fgblomqvist) [inline beta/src/components/header/index.ts]: When you're already at it, the nested div inside this button shouldn't be needed (I tried removing it with success). The `flex items-center` classes can just be applied directly to the button instead. The icon and span can go straight inside the button.

Comment (peterklingelhofer) [reply beta/src/components/header/index.ts]: Nice, addressed here: https://github.com/resonatecoop/stream/pull/216/commits/9bc22dbb95fb1298f4dab7216258f3ace5ce59f5

File: beta/src/components/header/index.ts (hunk 1 above)
Comment (peterklingelhofer) [reply beta/src/components/header/index.ts]: Good call, addressed here: https://github.com/resonatecoop/stream/pull/216/commits/45c7e7cf4dffd8596f586d8d6ee5befa740052aa

File: beta/src/components/header/index.ts (hunk 2 above)
Comment (peterklingelhofer) [reply beta/src/components/header/index.ts]: Good thinking! Cursor addressed here: https://github.com/resonatecoop/stream/pull/216/commits/e109eced12a77cde438cfa72cb3f7c82a5cbc640, and the former points are addressed here: https://github.com/resonatecoop/stream/pull/216/commits/45c7e7cf4dffd8596f586d8d6ee5befa740052aa

File: packages/search-component/index.js (hunk 3 above)
Comment (fgblomqvist) [reply packages/search-component/index.js]: Found it:
https://github.com/choojs/choo#pushstatestateeventspushstate

Some usages already:
https://github.com/resonatecoop/stream/search?q=pushState

Comment (peterklingelhofer) [reply packages/search-component/index.js]: I found this last night as well! Was too tired to implement. Will aim to get this working this evening. 🤩

Comment (peterklingelhofer) [reply packages/search-component/index.js]: Here we go: https://github.com/resonatecoop/stream/pull/216/commits/56a7f9c6e98dfcf5814a2d7382e3439723641bfc

@fgblomqvist, please let me know what you think, and if you think any further changes are needed. 😌

Comment (fgblomqvist) [reply packages/search-component/index.js]: Looks great now, sorry for the pickiness (not like I'm the authority anyway though) :smile:

**Review by fgblomqvist — APPROVED** [review]

File: packages/search-component/index.js (hunk 3 above)
Comment (peterklingelhofer) [reply packages/search-component/index.js]: Not at all, this is a way less clunky implementation. I appreciate the review. 😀
